[package]
name = "prometheus_exporter_test"
version = "0.0.1"
authors = ["danni@redislabs.com"]
edition = "2021"

[dependencies]
prometheus_exporter = "0.8.5"
reqwest = { version = "0.11.16", features = ["blocking"] }
rand = "0.7"
env_logger = "0.8"
log = { version = "0.4" }
clap = "2.33.3"
